import type { Metadata } from "next";
import "./globals.css";
import "@/assets/styles/global.scss";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({ weight: ["300", "400", "500", "600", "700", "800"], subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
